#!groovy
node{
    sh "serverless install --url ${params.url} --name ${params.service}"
    def file = new File("${env.WORKSPACE}/service")
    sh "echo ${params.service} >> ${file}"
     sh('git remote set-url origin https://github.com/ManasaMurthy/serverless.git')
      sh "git push"
}
