#!groovy

stage 'Install Project'
node{
    dir("${REPO_NAME}"){
   	   deleteDir()
     }
    sh 'git clone git@gitlab.com:ManasaMurthy/${REPO_NAME}.git'
}

stage 'Deploy'
node{
     dir("${REPO_NAME}") {
          if(env.WEB_PAGE_DEPLOYMENT_REQUIRED == 'true'){
                sh 'rm generate-form.js'
                sh 'wget https://s3.amazonaws.com/config-serverless/generate-form.js'
                sh 'node generate-form.js'
           }
       	   sh "serverless deploy --aws-profile ${params.profile}"
     }
}

stage 'Webpage installation'
node{
    dir("${REPO_NAME}"){
        withAWS(credentials: 'aws-cred') {
		s3Upload acl: 'PublicRead', bucket: "serverless-pipeline-aws", includePathPattern: '*.html', metadatas: [''],path: env.REPO_NAME, workingDir: "frontend/"
	}
        
    }
}
