#!groovy
stage 'Install Project'
node{
    cleanWs()
    try{
      git(
          url: "https://gitlab.com/ManasaMurthy/aws-node-simple-http-endpoint",
          credentialsId: 'ManasaMurthy',
          branch: 'master'
      )
    }catch(Exception e){
        currentBuild.result = 'FAILURE'
        throw e
    }
    //sh 'git clone git@gitlab.com:ManasaMurthy/${REPO_NAME}.git'
}

stage 'Deploy'
node{
     dir("${REPO_NAME}") {
                if(env.WEB_PAGE_DEPLOYMENT_REQUIRED == 'true'){
                    sh 'node generate-form.js'
                }
               sh "serverless deploy --aws-profile ${params.profile}"
        }
}

/*stage 'Webpage installation'
node{
    dir("${REPO_NAME}/frontend"){
        withAWS(credentials: credentialsId) {
		s3Upload acl: 'Private', bucket: "Serverless", includePathPattern: '*.html', metadatas: [''],path: env.REPO_NAME, workingDir: "target/scala-2.11/"
	}
        
    }
}*/

